import { 
  Wind, 
  Droplets, 
  Hammer, 
  Home, 
  CheckCircle, 
  User 
} from 'lucide-react';
import { TranslationData, ServiceItem, Review, Language } from './types';

export const TRANSLATIONS: Record<Language, TranslationData> = {
  id: {
    heroTitle: "Solusi Perawatan Properti Terpercaya di Bali",
    heroSubtitle: "Dari servis AC, perawatan kolam renang, hingga renovasi bangunan. Kami hadir untuk rumah dan villa Anda.",
    ctaButton: "Pesan Layanan",
    servicesTitle: "Layanan Kami",
    servicesSubtitle: "Apapun kebutuhan properti Anda, kami punya ahlinya.",
    whyUsTitle: "Mengapa BaleCare?",
    testimoniTitle: "Kata Pelanggan",
    bookModalTitle: "Formulir Pemesanan",
    nameLabel: "Nama Lengkap",
    phoneLabel: "Nomor WhatsApp",
    addressLabel: "Alamat / Lokasi Villa",
    dateLabel: "Rencana Jadwal",
    descLabel: "Deskripsi Masalah",
    submitButton: "Kirim Pesanan",
    successTitle: "Pesanan Diterima!",
    successMsg: "Tim kami akan segera menghubungi Anda via WhatsApp untuk konfirmasi.",
    footerText: "Melayani area Denpasar, Badung, Gianyar, dan Tabanan.",
    categories: {
      ac: "Service AC",
      pool: "Perawatan Kolam",
      plumbing: "Pipa & Air",
      renovation: "Renovasi & Cat",
      cleaning: "Deep Cleaning",
      garden: "Taman & Lanskap"
    },
    aiSectionTitle: "BaleCare Smart Tools ✨",
    aiDiagnoseTitle: "Diagnosa Masalah",
    aiDiagnoseDesc: "Bingung kenapa rumah rusak? Tanya AI ahlinya.",
    aiVillaTitle: "Buat Deskripsi Villa",
    aiVillaDesc: "Buat caption menarik untuk Airbnb/Booking Anda.",
    aiModalDiagnoseTitle: "Diagnosa Masalah Properti",
    aiModalVillaTitle: "Generator Deskripsi Villa",
    aiInputPlaceholder: "Contoh: Tembok kamar mandi rembes dan cat mengelupas...",
    aiVillaPlaceholder: "Contoh: Villa 2 lantai, kolam renang besar, dekat pantai Canggu, suasana tenang...",
    analyzeButton: "Analisa Sekarang",
    generateButton: "Buat Deskripsi",
    loading: "Sedang berpikir...",
    aiResultLabel: "Hasil Analisa AI:",
    copyText: "Salin Teks",
    bookRecommended: "Pesan Layanan Ini",
    addReviewBtn: "Tulis Ulasan",
    reviewModalTitle: "Bagikan Pengalaman Anda",
    reviewNamePlaceholder: "Nama Anda",
    reviewTextPlaceholder: "Ceritakan pengalaman service Anda...",
    submitReviewBtn: "Kirim Ulasan",
    reviewSuccessBtn: "Beri Ulasan Layanan",
    closeBtn: "Tutup",
    loginBtn: "Masuk dengan Google",
    logoutBtn: "Keluar",
    welcomeUser: "Halo,",
    guestName: "Tamu",
    guestLoginTitle: "Login Tamu Berhasil",
    guestLoginMsg: "Karena keterbatasan domain preview, Anda masuk sebagai Tamu. Anda tetap bisa menggunakan semua fitur!"
  },
  en: {
    heroTitle: "Trusted Property Care Solutions in Bali",
    heroSubtitle: "From AC service, pool maintenance, to building renovation. We are here for your home and villa.",
    ctaButton: "Book Service",
    servicesTitle: "Our Services",
    servicesSubtitle: "Whatever your property needs, we have the experts.",
    whyUsTitle: "Why BaleCare?",
    testimoniTitle: "Testimonials",
    bookModalTitle: "Booking Form",
    nameLabel: "Full Name",
    phoneLabel: "WhatsApp Number",
    addressLabel: "Address / Villa Location",
    dateLabel: "Preferred Schedule",
    descLabel: "Problem Description",
    submitButton: "Submit Order",
    successTitle: "Order Received!",
    successMsg: "Our team will contact you shortly via WhatsApp for confirmation.",
    footerText: "Serving Denpasar, Badung, Gianyar, and Tabanan areas.",
    categories: {
      ac: "AC Service",
      pool: "Pool Maintenance",
      plumbing: "Plumbing",
      renovation: "Renovation & Paint",
      cleaning: "Deep Cleaning",
      garden: "Garden & Landscape"
    },
    aiSectionTitle: "BaleCare Smart Tools ✨",
    aiDiagnoseTitle: "Smart Diagnose",
    aiDiagnoseDesc: "Not sure what's wrong? Ask our AI expert.",
    aiVillaTitle: "Villa Description",
    aiVillaDesc: "Generate catchy captions for your Airbnb listing.",
    aiModalDiagnoseTitle: "Property Issue Diagnoser",
    aiModalVillaTitle: "Villa Description Generator",
    aiInputPlaceholder: "Ex: Bathroom wall is leaking and paint is peeling...",
    aiVillaPlaceholder: "Ex: 2-story villa, large private pool, near Canggu beach, quiet atmosphere...",
    analyzeButton: "Analyze Now",
    generateButton: "Generate Description",
    loading: "Thinking...",
    aiResultLabel: "AI Analysis Result:",
    copyText: "Copy Text",
    bookRecommended: "Book This Service",
    addReviewBtn: "Write a Review",
    reviewModalTitle: "Share Your Experience",
    reviewNamePlaceholder: "Your Name",
    reviewTextPlaceholder: "Tell us about your service experience...",
    submitReviewBtn: "Submit Review",
    reviewSuccessBtn: "Rate Service",
    closeBtn: "Close",
    loginBtn: "Login with Google",
    logoutBtn: "Logout",
    welcomeUser: "Hi,",
    guestName: "Guest",
    guestLoginTitle: "Guest Login Success",
    guestLoginMsg: "Due to preview domain restrictions, you are logged in as Guest. You can still use all features!"
  }
};

export const SERVICES_DATA: ServiceItem[] = [
  { id: 'ac', icon: Wind, color: 'bg-blue-100 text-blue-600', price: 'Start IDR 75k' },
  { id: 'pool', icon: Droplets, color: 'bg-cyan-100 text-cyan-600', price: 'Start IDR 150k' },
  { id: 'plumbing', icon: Hammer, color: 'bg-orange-100 text-orange-600', price: 'By Inspection' },
  { id: 'renovation', icon: Home, color: 'bg-slate-100 text-slate-600', price: 'Project Based' },
  { id: 'cleaning', icon: CheckCircle, color: 'bg-green-100 text-green-600', price: 'Start IDR 50k/hr' },
  { id: 'garden', icon: User, color: 'bg-emerald-100 text-emerald-600', price: 'Monthly Package' },
];

export const INITIAL_REVIEWS: Review[] = [
  { name: "Sarah Jenkins", role: "Villa Owner (Canggu)", text: "Finally a reliable service in Bali! They fixed my AC and cleaned the pool on time.", rating: 5 },
  { name: "Budi Santoso", role: "Resident (Denpasar)", text: "Tukangnya sopan, kerjaan rapi, dan harganya transparan. Sangat rekomen untuk renovasi.", rating: 5 },
  { name: "Mike Lewis", role: "Expat (Ubud)", text: "Great English support. Booking via app was super easy. Keep it up!", rating: 4 },
];